services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=josephyusmita@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: "josephyusmita/trackin-web:latest"
    build:
      context: .
      dockerfile: ./docker/production/nginx/Dockerfile
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.trackin.rule=Host(`trackin.cloud`)"
      - "traefik.http.routers.trackin.entryPoints=websecure"
      - "traefik.http.routers.trackin.tls.certresolver=myresolver"
    volumes:
      # Mount the 'laravel-storage' volume to '/var/www/storage' inside the container.
      # -----------------------------------------------------------
      # This volume stores persistent data like uploaded files and cache.
      # The ':ro' option mounts it as read-only in the 'web' service because Nginx only needs to read these files.
      # The 'php-fpm' service mounts the same volume without ':ro' to allow write operations.
      # -----------------------------------------------------------
      - laravel_storage_production:/var/www/storage:ro
    networks:
      - laravel_production
      - traefik_public
    # ports:
    #   - "${NGINX_PORT:-80}:80"
    depends_on:
      php-fpm:
        condition: service_healthy # Wait for php-fpm health check

  php-fpm:
    # For the php-fpm service, we will create a custom image to install the necessary PHP extensions and setup proper permissions.
    image: "josephyusmita/trackin-php-fpm:latest"
    build:
      context: .
      dockerfile: ./docker/common/php-fpm/Dockerfile
      target: production # Use the 'production' stage in the Dockerfile
    restart: unless-stopped
    volumes:
      - laravel_storage_production:/var/www/storage # Mount the storage volume
    env_file:
      - .env.prod
    networks:
      - laravel_production
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    # The 'depends_on' attribute with 'condition: service_healthy' ensures that
    # this service will not start until the 'mysql' service passes its health check.
    # This prevents the application from trying to connect to the database before it's ready.
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: unless-stopped
    # MySQL images typically run as root internally to handle permissions,
    # so we usually omit the 'user' key here unless you have specific UID requirements.
    ports:
      - "${DB_PORT:-3306}:3306"
    environment:
      # MySQL requires a root password to be set
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      # Note the change in the internal path from /var/lib/mysqlql/data to /var/lib/mysql
      - mysql_data_production:/var/lib/mysql
    networks:
      - laravel_production
    # Health check for MySQL
    # -----------------------------------------------------------
    # Uses 'mysqladmin ping' to check if the server is responsive.
    # -----------------------------------------------------------
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped # Automatically restart unless the service is explicitly stopped
    networks:
      - laravel_production
    # Health check for Redis
    # -----------------------------------------------------------
    # Checks if Redis is responding to the 'PING' command.
    # This ensures that the service is not only running but also operational.
    # -----------------------------------------------------------
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  # Attach the service to the 'laravel_production' network.
  # -----------------------------------------------------------
  # This custom network allows all services within it to communicate using their service names as hostnames.
  # For example, 'php-fpm' can connect to 'mysql' by using 'mysql' as the hostname.
  # -----------------------------------------------------------
  laravel_production:
    name: laravel_production
  traefik_public:
    name: traefik_public

volumes:
  mysql_data_production:
  laravel_storage_production:
  letsencrypt:
